### ISSUE TITLE
doc.model is not a function

### ISSUE THREAD

**Issue by twoheaded** [Kubide/mongoose-slug-generator#11]
I get the following error:

```
TypeError: doc.model is not a function
    at makeUniqueCounterSlug (node_modules\mongoose-slug-generator\lib\slug-generator.js:142:9)
    at node_modules\mongoose-slug-generator\lib\slug-generator.js:91:21
    at node_modules\mongoose-slug-generator\node_modules\async\lib\async.js:181:20
```

when I try to add unique slugs for nested and parent schemas. 

Can you help me with this problem?

**Comment by YuriGor** [comment]
Implemented in [this fork](https://github.com/YuriGor/mongoose-slug-updater)
Same as in MongoDB, unique slugs in nested arrays elements will be unique over collection on per-document basis, so inside nested array duplicate slugs will still be possible.

**Comment by nikhillad01** [comment]
> Implemented in [this fork](https://github.com/YuriGor/mongoose-slug-updater)
> Same as in MongoDB, unique slugs in nested arrays elements will be unique over collection on per-document basis, so inside nested array duplicate slugs will still be possible.

This worked for me.. Thanks
