### ISSUE TITLE
I have this error and don't know how to fix it. Please help me

### ISSUE THREAD

**Issue by huynhdev24** [Kubide/mongoose-slug-generator#20]
C:\shop\shop-api\node_modules\mongoose\lib\query.js:4281
    throw new MongooseError('Query.prototype.exec() no longer accepts a callback');   
          ^

MongooseError: Query.prototype.exec() no longer accepts a callback
    at model.Query.exec (C:\shop\shop-api\node_modules\mongoose\lib\query.js:4281:11) 
    at makeUniqueShortIdSlug (C:\shop\shop-api\node_modules\mongoose-slug-generator\lib\slug-generator.js:178:57)
    at C:\shop\shop-api\node_modules\mongoose-slug-generator\lib\slug-generator.js:86:21
    at C:\shop\shop-api\node_modules\async\lib\async.js:181:20
    at Object.async.forEachOf.async.eachOf (C:\shop\shop-api\node_modules\async\lib\async.js:233:13)
    at Object.async.forEach.async.each (C:\shop\shop-api\node_modules\async\lib\async.js:209:22)
    at model.<anonymous> (C:\shop\shop-api\node_modules\mongoose-slug-generator\lib\slug-generator.js:74:15)
    at callMiddlewareFunction (C:\shop\shop-api\node_modules\kareem\index.js:628:27)  
    at next (C:\shop\shop-api\node_modules\kareem\index.js:93:7)
    at model.next (C:\shop\shop-api\node_modules\kareem\index.js:117:9)

**Comment by huynhdev24** [comment]
![image](https://user-images.githubusercontent.com/124909303/227688290-30d57903-e4c4-452e-af2a-431b521f7bc9.png)

**Comment by huynhdev24** [comment]
![image](https://user-images.githubusercontent.com/124909303/227688455-dbf0be75-68d4-47b3-8911-6c900f711194.png)
